// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StackOverflowClone.Data;

#nullable disable

namespace StackOverflowClone.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("StackOverflowClone.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("StackOverflowClone.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Explain ASP.NET Core.",
                            PostedBy = "Mobinul Ahasan Tanjid",
                            PostedDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "What is ASP.NET Core?"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Explain EF Core.",
                            PostedBy = "Mohammad Shakil",
                            PostedDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "What is EF Core?"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Describe the concept of Dependency Injection and how it is implemented in ASP.NET Core.",
                            PostedBy = "Joy Datta",
                            PostedDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "What is Dependency Injection in .NET?"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Explain what middleware is and how it works in the request pipeline.",
                            PostedBy = "Rahmatullah Rony",
                            PostedDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "What is Middleware in ASP.NET Core?"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Discuss the layers and benefits of using Clean Architecture in .NET applications.",
                            PostedBy = "Simanta Saha",
                            PostedDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "What is Clean Architecture?"
                        },
                        new
                        {
                            Id = 6,
                            Body = "Explain how EF Core Migrations help in database versioning and schema updates.",
                            PostedBy = "Mohammmad Noor",
                            PostedDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "What is Entity Framework Core Migration?"
                        },
                        new
                        {
                            Id = 7,
                            Body = "Describe the role of controllers and actions in handling HTTP requests.",
                            PostedBy = "MD Abu Taseen",
                            PostedDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "What are Controllers in ASP.NET Core MVC?"
                        },
                        new
                        {
                            Id = 8,
                            Body = "Highlight the key differences between .NET Framework and .NET Core.",
                            PostedBy = "Mobinul Ahasan Tanjid",
                            PostedDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "What is the difference between .NET Framework and .NET Core?"
                        },
                        new
                        {
                            Id = 9,
                            Body = "Explain why Data Transfer Objects are used and how they improve API design.",
                            PostedBy = "Mohammad Shakil",
                            PostedDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "What are DTOs in Web API?"
                        },
                        new
                        {
                            Id = 10,
                            Body = "Explain attribute routing and conventional routing with examples.",
                            PostedBy = "Joy Datta",
                            PostedDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "What is Routing in ASP.NET Core?"
                        });
                });

            modelBuilder.Entity("StackOverflowClone.Models.Answer", b =>
                {
                    b.HasOne("StackOverflowClone.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("StackOverflowClone.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
